services:
  php:
    image: strarsis/docker-php-bedrock:8.3.13-fpm
    container_name: bedrock_php-fpm
    volumes:
      - ./bedrock:/srv/www
  nginx:
    image: nginx:latest
    container_name: bedrock_nginx
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - ./bedrock:/srv/www
      - ./nginx/host.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  db:
    image: mysql:8.0.40-bookworm
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password