version: '3.1'

services:

  apache-php-1:
    build: ./docker
    restart: always
    ports:
      - 8082:80
    volumes:
      - ./bedrock:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

volumes:
  apache-php-1:
  db: