version: '3.4'

services:

  php:
    build:
      context: .
      target: bedrockapp_php
  nginx:
    build:
      context: .
      target: bedrockapp_nginx
    depends_on:
      - php
    ports:
      - "80:80"
