version: '3.4'

services:

  php-fpm:
    build:
      context: .
      target: bedrockapp_php
  nginx:
    build:
      context: .
      target: bedrockapp_nginx
    depends_on:
      - php-fpm
    ports:
      - "8082:80"
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
