version: '3.4'

services:

  php:
    build:
      context: .
      target: bedrockapp_php
    volumes:
      - ./bedrock/composer.json:/var/www/html/composer.json
      - ./bedrock/composer.lock:/var/www/html/composer.lock
      - ./bedrock/web/app/uploads/:/var/www/html/web/app/uploads/
  nginx:
    build:
      context: .
      target: bedrockapp_nginx
    depends_on:
      - php
    ports:
      - "8082:80"
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
